<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="2" total="4" passed="0">
  <reporter-output>
    <line>
      <![CDATA[=============Browser Session Started========]]>
    </line>
    <line>
      <![CDATA[=============Browser Session Ended========]]>
    </line>
    <line>
      <![CDATA[=============Browser Session Started========]]>
    </line>
    <line>
      <![CDATA[=============Browser Session Ended========]]>
    </line>
  </reporter-output>
  <suite name="IDM TEST" duration-ms="33514" started-at="2018-05-15T06:20:45Z" finished-at="2018-05-15T06:21:18Z">
    <groups>
    </groups>
    <test name="TEST IDM" duration-ms="33514" started-at="2018-05-15T06:20:45Z" finished-at="2018-05-15T06:21:18Z">
      <class name="com.test.scripts.trackUser">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.test.scripts.trackUser@1b604f19]" name="setup" is-config="true" duration-ms="11845" started-at="2018-05-15T11:50:59Z" finished-at="2018-05-15T11:51:11Z">
          <reporter-output>
            <line>
              <![CDATA[=============Browser Session Started========]]>
            </line>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="trackUser_reg()[pri:0, instance:com.test.scripts.trackUser@1b604f19]" name="trackUser_reg" duration-ms="6079" started-at="2018-05-15T11:51:11Z" finished-at="2018-05-15T11:51:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.assertNotEquals(Assert.java:832)
	at org.testng.Assert.assertNotEquals(Assert.java:837)
	at com.test.scripts.trackUser.trackUser_reg(trackUser.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- trackUser_reg -->
        <test-method status="PASS" signature="closeApplication(org.testng.ITestResult)[pri:0, instance:com.test.scripts.trackUser@1b604f19]" name="closeApplication" is-config="true" duration-ms="737" started-at="2018-05-15T11:51:17Z" finished-at="2018-05-15T11:51:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=trackUser_reg status=FAILURE method=trackUser.trackUser_reg()[pri:0, instance:com.test.scripts.trackUser@1b604f19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[=============Browser Session Ended========]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- com.test.scripts.trackUser -->
      <class name="com.test.scripts.sys_admin">
        <test-method status="PASS" signature="setExtent()[pri:0, instance:com.test.scripts.sys_admin@1593948d]" name="setExtent" is-config="true" duration-ms="231" started-at="2018-05-15T11:50:45Z" finished-at="2018-05-15T11:50:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.test.scripts.sys_admin@1593948d]" name="setup" is-config="true" duration-ms="13500" started-at="2018-05-15T11:50:45Z" finished-at="2018-05-15T11:50:58Z">
          <reporter-output>
            <line>
              <![CDATA[=============Browser Session Started========]]>
            </line>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="test_sysadminUrl()[pri:0, instance:com.test.scripts.sys_admin@1593948d]" name="test_sysadminUrl" duration-ms="76" started-at="2018-05-15T11:50:58Z" finished-at="2018-05-15T11:50:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [403 Forbidden] but found [Login - Oracle Access Management 11g]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [403 Forbidden] but found [Login - Oracle Access Management 11g]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.test.scripts.sys_admin.test_sysadminUrl(sys_admin.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_sysadminUrl -->
        <test-method status="PASS" signature="closeApplication(org.testng.ITestResult)[pri:0, instance:com.test.scripts.sys_admin@1593948d]" name="closeApplication" is-config="true" duration-ms="605" started-at="2018-05-15T11:50:58Z" finished-at="2018-05-15T11:50:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test_sysadminUrl status=FAILURE method=sys_admin.test_sysadminUrl()[pri:0, instance:com.test.scripts.sys_admin@1593948d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[=============Browser Session Ended========]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.test.scripts.sys_admin@1593948d]" name="endReport" is-config="true" duration-ms="411" started-at="2018-05-15T11:51:18Z" finished-at="2018-05-15T11:51:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.test.scripts.sys_admin -->
    </test> <!-- TEST IDM -->
  </suite> <!-- IDM TEST -->
</testng-results>
